src/app/app.module.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts
src/app/services/wizard-guard.service.ts

[web wallet] refs #31 Implement route guard to redirect to wizard

[web wallet] refs #31 Implement route guard to redirect to wizard

---

e2e/wallets.e2e-spec.ts
e2e/wallets.po.ts
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.css
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.html
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.scss
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.ts

ref #33 Add layout for decrypt wallet

[web wallet] fixes #33 Add layout for decrypt wallet

---

src/app/components/layout/header/header.component.html
src/app/components/pages/history/history.component.html
src/app/components/pages/send-skycoin/send-skycoin.component.html
src/app/components/pages/send-skycoin/send-skycoin.component.ts
src/app/components/pages/wallets/address-detail/wallet-detail.component.html
src/app/components/pages/wallets/address-detail/wallet-detail.component.ts
src/app/components/pages/wallets/wallets.component.html
src/app/services/wallet.service.ts

* Improve security for generating new addresses
* Remove rounding errors
* Fix bugs in sending page
* Hide add address button for locked wallet
* Remove dead code

Fixing bugs

---

src/app/services/wallet.service.spec.ts
src/app/services/wallet.service.ts

Fixes #76 
Changes:
- load balances when user creates/loads a wallet

Issue #76: The balance is not being updated

---

src/app/components/layout/header/header.component.scss

Fixes #85 
Changes:
- changes in style of header

Issue #85: Fix the header style

---

src/app/components/pages/send-skycoin/send-skycoin.component.html
src/app/components/pages/send-skycoin/send-skycoin.component.spec.ts
src/app/components/pages/send-skycoin/send-skycoin.component.ts
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.ts
src/app/components/pages/wallets/wallets.component.ts
src/app/services/wallet.service.ts
src/app/utils/index.ts

Fixes #73
Changes: 
"Unlock Wallet" modal appears in case the wallet has not been previously unlocked by user.
"Send from" drop down disables only empty wallets, but shows locked wallets.

#73 - Most of the time it is not possible to sign transactions

---

src/app/components/pages/history/transaction-detail/transaction-detail.component.html

Fixes #88 
Changes:
- in transaction detail page: show transaction id, show full address

Issue #88: Incomplete data in TransactionDetailComponent

---

src/app/services/cipher.provider.spec.ts

Fixes #50 
Changes:
- unit tests for Cipher provider

Issue #50: add unit tests for Cipher provider

---

src/app/services/wallet.service.ts

Fixes #95 
Changes:
- corrections in balance calculation

Issue #95: The balance of the addresses is calculated incorrectly

---

package-lock.json
package.json
src/app/app.module.ts
src/app/components/pages/settings/pending-transactions/pending-transactions.component.html
src/app/components/pages/settings/pending-transactions/pending-transactions.component.scss
src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
src/styles.scss

Fixes #97 
Changes:
- ngx-datatable package was removed;
- pending transactions page has the similar design as in the outputs page

Issue #97: Remove ngx-datatable

---

src/app/app.module.ts
src/app/components/pages/send-skycoin/send-skycoin.component.html
src/app/components/pages/send-skycoin/send-skycoin.component.ts
src/app/directives/number-field.directive.spec.ts
src/app/directives/number-field.directive.ts

Fixes #86 
Changes:
- in send coin page: change validator for amount value, update reset form values
- new directive was created to allow specify only numbers

Issue #86: Coins validation issues

---

src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/outputs/outputs.component.ts
src/app/services/api.service.ts
src/app/services/wallet.service.ts

Fixes #102 
Changes:
- The outputs page shows the value of calculated_hours, not the value of hours
- Apply GetOutputsRequestOutput[] type  for the outputs object
- Minor refactoring of the outputs component

Issue #102: The outputs page shows an incorrect number of hours

---

src/app/app.datatypes.ts
src/app/services/api.service.spec.ts
src/app/services/api.service.ts
src/app/services/wallet.service.spec.ts
src/app/services/wallet.service.ts

Fixes #105 
Changes:
- Output.hours has been renamed to calculated_hours is in app.datatypes.ts
- Minor refactoring of involved components

Issues #105: Output.hours should be renamed

---

src/app/components/pages/send-skycoin/send-skycoin.component.ts

Fixes #121 
Changes:
- trim specified address before sending.

Issue #121: The destination addresses must be cleaned

---

src/app/services/wallet.service.ts

Fixes #129
Changes: The unused functions have been removed:
- private retrieveAddressBalance
- private retrieveInputAddress
- private retrieveWalletBalance
- private retrieveWalletTransactions
- private retrieveWallets

Issue #129: There are unused functions in WalletService

---

src/app/components/layout/header/header.component.html
src/app/components/layout/header/header.component.ts

Fixes #127 
Changes:
- simplify a bit loading indicator;
- change logic of showing the blockchain progress.

Issue #127: The header shows invalid data when opening the wallet.

---

src/app/services/wallet.service.ts

Fixes #135 
Changes:
- in sendSkycoin(): fix how many hours to return.

Issue #135: Problem when calculating how many hours to return

---

README.md

Fixes # non reported
Changes:
- Adds cryptography info to README.md
Please check if the information is adequate.

Add cryptography info to README.md

---

e2e/onboarding-create.e2e-spec.ts
src/app/services/wallet.service.ts

Fixes #139 
Changes:
- Timer has been run outside the Angular zone
- Re moved "browser.waitForAngularEnabled"

Issue #139: The balance update timer should run outside the Angular zone

---

src/app/services/wallet.service.ts

Fixes #145 
Changes:
- condition of updating balance

Issue #145: The updating process may fail

---

src/app/components/pages/send-skycoin/send-skycoin.component.ts
src/app/services/wallet.service.ts

Fixes #124 
Changes:
- update balance after transaction has been sent;
- in walletService.sendSkycoins(): convert amount once `parseInt(amount * 1000000 + '', 10)` and reuse it in other places (avoid code duplication).

Issue #124: The balance must be updated after sending transactions

---

Makefile
docker-proxy.config.js

Fixes #154 
Changes:
- docker configuration

Issue #154: Change web interface address for docker

---

src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/outputs/outputs.component.scss

Fixes #158 
Changes:
- style improvements in outputs page

#158: Style improvements

---

e2e/wallets.po.ts
src/app/components/pages/wallets/address-detail/wallet-detail.component.html
src/app/components/pages/wallets/address-detail/wallet-detail.component.scss
src/app/components/pages/wallets/address-detail/wallet-detail.component.spec.ts
src/app/components/pages/wallets/address-detail/wallet-detail.component.ts
src/app/components/pages/wallets/wallets.component.html
src/app/components/pages/wallets/wallets.component.scss
src/app/components/pages/wallets/wallets.component.ts
src/styles.scss

Fixes #157 
Changes:
- the style of the wallets page;

#157: Update the style of the wallets page

---

src/app/components/layout/header/header.component.html
src/app/components/layout/header/header.component.ts
src/app/components/layout/header/top-bar/top-bar.component.html
src/app/components/layout/header/top-bar/top-bar.component.ts
src/app/components/layout/modal/modal.component.html
src/app/components/layout/modal/modal.component.ts
src/app/components/layout/qr-code/qr-code.component.html
src/app/components/pages/history/history.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-disclaimer/onboarding-disclaimer.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-safeguard/onboarding-safeguard.component.html
src/app/components/pages/send-skycoin/send-skycoin.component.html
src/app/components/pages/settings/blockchain/blockchain.component.html
src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/pending-transactions/pending-transactions.component.html
src/app/components/pages/wallets/change-name/change-name.component.html
src/app/components/pages/wallets/create-wallet/create-wallet.component.html
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.html
src/app/components/pages/wallets/wallets.component.html

Fixes #167 
Changes:
- Rename `title` property to `headline` in the following components: ModalComponent, TopBarComponent, HeaderComponent

#167: Some unnecessary tooltips are being shown

---

src/app/components/pages/history/history.component.scss
src/app/components/pages/send-skycoin/send-skycoin.component.scss
src/app/components/pages/settings/blockchain/blockchain.component.scss

Fixes #176 
Changes:
- left and right lateral margins in the blockchain / history / send coins pages.

#176: The lateral margins are not consistent

---

src/app/app.module.ts
src/app/components/layout/confirmation/confirmation.component.html
src/app/components/layout/confirmation/confirmation.component.scss
src/app/components/layout/confirmation/confirmation.component.spec.ts
src/app/components/layout/confirmation/confirmation.component.ts
src/app/components/pages/wallets/address-detail/wallet-detail.component.html
src/app/components/pages/wallets/address-detail/wallet-detail.component.ts
src/app/services/wallet.service.ts

Fixes #177 
Changes:
- added button to delete a wallet;
- added method to delete a wallet;
- added confirmation component;
- show confirmation message before actual delete a wallet.

#177: Add an option to delete wallets

---

src/app/components/layout/button/button.component.html
src/app/components/layout/button/button.component.ts

Fixes #161 
Changes:
- in button component, show error message in the button.

#161: Show the error msg in the buttons

---

src/app/components/layout/button/button.component.ts

Fixes #189 
Changes:
- Fixed Errors handling in ButtonComponent

#189: Errors in ButtonComponent

---

e2e/onboarding-create.e2e-spec.ts
e2e/onboarding-create.po.ts
e2e/wallets.e2e-spec.ts
e2e/wallets.po.ts

Fixes #187 
Changes:
- add e2e tests

#187: Add e2e test(s) for "Prevent the user from adding more than one wallet with the same seed

---

src/app/components/layout/confirmation/confirmation.component.ts
src/app/components/layout/header/header.component.html
src/app/components/layout/header/header.component.spec.ts
src/app/components/layout/header/nav-bar/nav-bar.component.html
src/app/components/layout/header/nav-bar/nav-bar.component.spec.ts
src/app/components/layout/header/top-bar/top-bar.component.html
src/app/components/layout/qr-code/qr-code.component.html
src/app/components/layout/qr-code/qr-code.component.spec.ts
src/app/components/pages/buy/add-deposit-address/add-deposit-address.component.html
src/app/components/pages/buy/add-deposit-address/add-deposit-address.component.spec.ts
src/app/components/pages/buy/add-deposit-address/add-deposit-address.component.ts
src/app/components/pages/buy/buy.component.html
src/app/components/pages/buy/buy.component.spec.ts
src/app/components/pages/buy/buy.component.ts
src/assets/i18n/en.json

Fixes #151 
Changes:
- Fixed buy related components
- Fixed layout related components

#151: Use ngx-translate for the texts: Layout and buy related components

---

src/app/components/layout/button/button.component.ts
src/app/components/pages/send-skycoin/send-verify/send-verify.component.ts
src/app/utils/errors.spec.ts
src/app/utils/errors.ts

Fixes #190 
Changes:
- setEnabled() method has been added to the ButtonComponent
- OnDestroy hook has been implemented by the SendVerifyComponent component to disable toaster notifications
Comment: The problem with multiplied coins value will be fixed in scope of the issue #188

#190: If the transaction fails, the preview is left in an invalid state

---

src/app/components/pages/send-skycoin/send-form/send-form.component.html
src/app/components/pages/send-skycoin/send-form/send-form.component.ts

Fixes #204
Changes:
- the "notes" field is deleted from the send coins form.

#204: The "notes" field should be deleted

---

src/app/components/pages/wallets/address-detail/wallet-detail.component.html
src/app/components/pages/wallets/wallets.component.html

Fixes #211 
Changes:
- "SKY Hours" and "Balance" columns has been swapped

#211: Change order of "SKY Hours" and "Balance" column

---

.travis.yml
Makefile
src/app/app.datatypes.ts
src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html

Fixes #205 
Changes:
- update `transaction-info` component: show balance only if it's not preview;
- update `.travis.yaml`: add script to perform a production build.

#205: Prod build error

---

src/app/components/layout/double-button/double-button.component.html
src/app/components/layout/header/header.component.html
src/app/components/layout/header/top-bar/top-bar.component.html
src/app/components/layout/modal/modal.component.html
src/app/components/layout/qr-code/qr-code.component.html
src/app/components/pages/history/history.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-disclaimer/onboarding-disclaimer.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-safeguard/onboarding-safeguard.component.html
src/app/components/pages/send-skycoin/send-form/send-form.component.html
src/app/components/pages/send-skycoin/send-skycoin.component.html
src/app/components/pages/send-skycoin/send-skycoin.component.spec.ts
src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html
src/app/components/pages/settings/blockchain/blockchain.component.html
src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/pending-transactions/pending-transactions.component.html
src/app/components/pages/wallets/address-detail/wallet-detail.component.html
src/app/components/pages/wallets/change-name/change-name.component.html
src/app/components/pages/wallets/create-wallet/create-wallet.component.html
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.html
src/app/components/pages/wallets/wallets.component.html
src/assets/i18n/en.json

Fixes #215 
Changes:
- Fixes related to ngx-translate
- Refactoring of the layout related components

#215: Fixes related to ngx-translate

---

src/app/services/price.service.ts

Fixes #210 
Changes:
- get market price periodically.

#210: Update the market price periodically

---

src/app/services/wallet.service.ts

Fixes #166 
Changes:
- added a flag to determine whether the balance calculation has finished.

#166: Optimizations for balance updating

---

src/app/components/pages/send-skycoin/send-verify/send-verify.component.spec.ts

Fixes #221 
Changes:
- in unit-test: use mock class instead of empty value.

#221: Fix error during execution of SendVerificationComponent unit-test

---

src/app/components/layout/modal/modal.component.html
src/app/components/layout/modal/modal.component.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-safeguard/onboarding-safeguard.component.html

Fixes #208 
Changes:
- Added possibility to close OnboardingSafeguardComponent modal
- Close button is hidden on  OnboardingDisclaimerComponent

#208: Update the "disableDismiss" value in some modal windows

---

src/app/components/pages/history/history.component.ts
src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html

Fixes #231
Changes:
- removed coins from transaction-info component;
- the balance is centered vertically in transaction-info component.

#231: Improvements for the preview of transactions

---

src/app/components/layout/header/header.component.ts

Fixes #213 
Changes:
- The wallet shows "Loading" until balance is obtained

#213: The wallet shows 0 coins while loading

---

src/app/components/layout/header/top-bar/top-bar.component.html
src/app/components/layout/header/top-bar/top-bar.component.scss
src/app/components/layout/header/top-bar/top-bar.component.spec.ts
src/app/components/layout/header/top-bar/top-bar.component.ts
src/app/services/wallet.service.ts
src/assets/i18n/en.json

Fixes #240 
Changes:
- Blinking icon in the header added in case any issue with updating the balance
-  Tooltip with the "Connection error, retrying" text has been added on the warning item
- Unit tests have been adjusted

#240: Indicate if there was a problem updating the balance 

---

src/app/components/layout/header/header.component.ts
src/app/services/blockchain.service.ts

Fixes #237
Changes:
-  show an error message in case of connection error during obtaining node status.

#237: Problems obtaining node status

---

src/app/services/cipher.provider.lib.spec.ts

Fixes #256 
Changes:
- added additional tests for generate address.

#256: Improve the cipher test suite (part 1)

---

e2e/onboarding-create.e2e-spec.ts
e2e/onboarding-create.po.ts

Fixes #262 
Changes:
- added a test to make sure that the disclaimer modal window can not be closed by pressing the X button;
- added a test to load a wallet and check if the loaded wallet has the correct address.

#262: add additional e2e tests for onboarding page

---

src/app/services/cipher.provider.lib.spec.ts
src/app/services/cipher.provider.spec.ts
src/app/services/wallet.service.ts
src/app/utils/converters.ts

Fixes #281 
Changes:
- Repeated convertAsciiToHexa function has been moved to the "\src\app\utils\converters.ts" file

#281: Use only one convertAsciiToHexa function

---

e2e/wallets.e2e-spec.ts
e2e/wallets.po.ts
src/app/components/pages/wallets/create-wallet/create-wallet.component.ts
src/app/services/cipher.provider.spec.ts
src/app/services/cipher.provider.ts
src/app/services/wallet.service.ts

Fixes #287 
Changes:
- removed unused imports in wallet service;
- removed translateService from cipher provider;
- show error in a button in case of any error  during creation a wallet;
- skip saving a wallet in case of unblocking;

#287: Various fixes

---

src/app/constants/cipher-test-mode.const.ts
src/app/services/cipher.provider.lib.spec.ts
src/environments/environment.cipher-test.ts
src/environments/environment.prod.ts
src/environments/environment.ts
src/test.ts

Fixes #267 
Changes:
- added cipher test mode enum;
- updated cipher tests;

#267: Improve the cipher test suite (part 3)

---

src/app/services/cipher.provider.spec.ts
src/app/services/cipher.provider.ts
src/app/services/wallet.service.spec.ts
src/app/services/wallet.service.ts

Fixes #304 
Changes:
- updated transaction creation by using web worker

#304: Create transactions with the web worker

---

src/assets/scripts/cipher-web-worker.js

Fixes #312 
Changes:
- added `break` for each `case` body.

#312: Fix cipher-web-worker

---

src/app/components/pages/wallets/address-detail/wallet-detail.component.scss

Fixes #315 
Changes:
- margin of the QR code button

#315: Margin of the QR code button

---

e2e/wallets.po.ts
src/app/components/pages/wallets/address-detail/wallet-detail.component.html
src/app/components/pages/wallets/address-detail/wallet-detail.component.scss
src/app/components/pages/wallets/address-detail/wallet-detail.component.ts
src/styles.scss

Fixes #310
Changes:
- show spinner when new wallet address is creating;
- fix e2e tests;

#310: Show a loading animation while adding a new address

---

src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts

Fixes #305 
Changes:
- disable and hide buttons during wallet creation

#305: Block navigation while creating a wallet in the wizard

---

src/app/app.module.ts
src/app/components/layout/loading-content/loading-content.component.html
src/app/components/layout/loading-content/loading-content.component.scss
src/app/components/layout/loading-content/loading-content.component.spec.ts
src/app/components/layout/loading-content/loading-content.component.ts
src/app/components/pages/history/history.component.html
src/app/components/pages/history/history.component.ts
src/app/components/pages/settings/blockchain/blockchain.component.html
src/app/components/pages/settings/blockchain/blockchain.component.ts
src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/outputs/outputs.component.ts
src/app/components/pages/settings/pending-transactions/pending-transactions.component.html
src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
src/assets/i18n/en.json
src/styles.scss

Fixes #314 
Changes:
- added new component `loading-content`;
- show `loading-content` component when data is loading or no data.

#314: Indicate the status of the secondary pages

---

src/app/app.module.ts
src/app/services/coin.service.spec.ts
src/app/services/coin.service.ts

Fixes #308 
Changes:
- added coin service.

#308: Create CoinService

---

.angular-cli.json
src/app/services/cipher.provider.lib.spec.ts

Fixes #316
Changes:
- remove main.js

#316: Remove main.js from .angular-cli.json

---

src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
src/app/services/nav-bar.service.ts

Fixes #331
Changes:
- cleared transactions array before switching between "Mine", and "All";
- set initial state for header switcher.

#331: Problems in the pending transactions page

---

src/app/components/layout/button/button.component.scss
src/app/components/pages/send-skycoin/send-form/send-form.component.scss
src/app/components/pages/send-skycoin/send-verify/send-verify.component.scss

Fixes #332
Changes:
- updated the margins of ButtonComponent.

#332: Fix the margins of ButtonComponent

---

src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/outputs/outputs.component.ts

Fixes #329
Changes:
- updates in outputs page.

#329: Hide wallets and addresses without outputs, in the outputs page

---

src/app/coins/basecoin.ts
src/app/coins/skycoin.coin.ts
src/app/coins/test.coin.ts
src/app/constants/coins-id.const.ts
src/app/services/price.service.spec.ts
src/app/services/price.service.ts

Fixes #335
Changes:
- get price info using current coin;

#335: Get the CMC ticker ID from CoinService

---

src/app/app.module.ts
src/app/components/layout/loading-content/loading-content.component.spec.ts
src/app/components/layout/select-coin/select-coin.component.html
src/app/components/layout/select-coin/select-coin.component.scss
src/app/components/layout/select-coin/select-coin.component.spec.ts
src/app/components/layout/select-coin/select-coin.component.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.html
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.spec.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts
src/app/components/pages/wallets/create-wallet/create-wallet.component.html
src/app/components/pages/wallets/create-wallet/create-wallet.component.spec.ts
src/app/components/pages/wallets/create-wallet/create-wallet.component.ts
src/app/services/wallet.service.spec.ts
src/app/services/wallet.service.ts
src/assets/i18n/en.json

Fixes #342 
Changes:
- added new component to select a coin from the list of available coins (will be reused in scope of #343);
- added ability to select coin when user is going to create a wallet (with predefined value);
- added appropriate unit-tests;
- fixed incorrect naming of LoadingContentComponent test.

#342: Allow to select the coin while creating a wallet

---

src/app/components/layout/modal/modal.component.html
src/app/components/layout/modal/modal.component.scss
src/app/components/layout/modal/modal.component.spec.ts
src/app/components/layout/modal/modal.component.ts
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.html
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.ts
src/app/services/wallet.service.spec.ts
src/app/services/wallet.service.ts

Fixes #333 
Changes:
- add event emiter into `walletService.unlockWallet()`;
- show progress bar during unlocking a wallet;
- fix unit-tests;

#333: Show progress when unlocking a wallet

---

src/app/components/layout/header/header.component.html
src/app/components/layout/header/header.component.scss
src/app/components/layout/header/header.component.ts
src/app/components/layout/select-coin/select-coin.component.html
src/app/components/layout/select-coin/select-coin.component.ts
src/app/components/pages/history/history.component.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.spec.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts
src/app/components/pages/settings/outputs/outputs.component.ts
src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
src/app/components/pages/wallets/wallets.component.html
src/app/services/coin.service.ts
src/app/services/wallet.service.cipher.spec.ts
src/app/services/wallet.service.spec.ts
src/app/services/wallet.service.ts
src/app/services/wizard-guard.service.ts
src/assets/i18n/en.json
src/styles.scss

Fixes #343 
Changes:
- Header select box with coins
- Adaptation of components and services for changing coins

#343: Allow to change the current coin

---

src/app/services/wallet.service.spec.ts
src/app/services/wallet.service.ts
src/assets/i18n/en.json

Fixes #357 
Changes:
- fixed errors in the texts
- unit tests have been adjusted

#357: Errors in the texts

---

src/app/services/wallet.service.ts

Fixes #356
Changes:
- Ability to create different coin types with the same seed

#356: Problem when trying to create a wallet with an already used seed

---

src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts
src/app/components/pages/wallets/create-wallet/create-wallet.component.ts

Fixes #355 
Changes:
- Coin changes in case user create a new wallet with different type of coin

#355: Change the coin after creating a wallet

---

src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.scss

Fixes #365 
Changes:
- A 20px margin has been added to the lower part of the wizard

#365: The wizard needs a lower margin

---

src/app/components/pages/wallets/wallet-detail/wallet-detail.component.scss

Fixes #368 
Changes:
- Copy button area was expanded to cover all copy area

#368: Improve the behavior of the "copy" text

---

src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.spec.ts
src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts
src/app/services/wallet.service.ts
src/app/services/wizard-guard.service.ts

Fixes #366 
Changes:
- Small improvements for the code have been done

#366: Small improvements for the code

---

src/assets/i18n/en.json

Fixes #377
Changes:
- the confirmation text when user deletes a wallet

#377: Improve the alert displayed when deleting a wallet

---

src/app/components/layout/header/nav-bar/nav-bar.component.scss
src/app/components/layout/header/top-bar/top-bar.component.scss
src/app/components/layout/modal/modal.component.scss
src/app/components/pages/history/history.component.scss
src/app/components/pages/history/transaction-detail/transaction-detail.component.scss
src/app/components/pages/wallets/wallets.component.html
src/app/components/pages/wallets/wallets.component.scss

Fixes #375 
Changes:
- Hoover effects have been added to the following elements:
- wallet row and down arrow button
- unlock wallet button
- unselected navigation menu buttons
-  transaction history row 
- buttons of the "top bar" menu
- "x" button on the modal component
- "x" button on the transaction modal component

#375: Add :hover to the buttons

---

src/app/components/layout/button/button.component.scss

Fixes #381
Changes:
- in button css style.

#381: Fix the buttons highlighting

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.config.ts
src/app/app.module.ts
src/app/components/layout/header/header.component.html
src/app/components/layout/header/header.component.spec.ts
src/app/components/layout/header/header.component.ts
src/app/services/blockchain.service.ts
src/app/services/language.service.spec.ts
src/app/services/language.service.ts
src/app/utils/test-mocks.ts
src/assets/i18n/en.json
src/assets/i18n/tst.json
src/styles.scss

Fixes #382
Changes:
- added test language file `tst.json`, the whole texts are the same as in English but with prefix `TST:`.
- added ability to change current language;
- created separate service `languageService` to encapsulate manipulation with languages;
- updated/added appropriate unit tests.

#382: Add the option to change language

---

src/app/services/blockchain.service.ts

Fixes #376
Changes:
- change interval period if the node is almost synchronized

#376: Refresh faster if the node is almost synchronized

---

src/app/components/pages/history/history.component.scss
src/app/components/pages/wallets/wallets.component.html
src/assets/i18n/en.json
src/assets/i18n/tst.json

Fixes #396
Changes:
- "Encryption" renamed to "Locked"
- "Time since last block" replaced by "Timestamp of last block:"
- transaction history amount aligned to right

#396: UI Fixes

---

src/app/app.config.ts
src/app/components/layout/header/header.component.html
src/app/components/layout/header/top-bar/top-bar.component.html
src/app/components/layout/header/top-bar/top-bar.component.scss
src/app/components/pages/settings/blockchain/blockchain.component.html
src/assets/i18n/en.json
src/assets/i18n/es.json
src/assets/i18n/tst.json

Changes:
- `es.json` was added, with the texts in Spanish, and the language was added to `config.languages`.
- The `top-bar.*` text are now inside `header`, in the languaje files.
- A parameter was added to some text variables, in order to get the translated text with a single call to the `translate` pipe, instead of having to build the text by concatenating several strings.
- The "loading" texts now have 3 points at the end, instead of 2.

Add Spanish translation

---

src/app/services/wallet.service.ts

Fixes #404
Changes:
- shows transactions between user's addresses in tx history

Show transactions between user's addresses

---

src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/outputs/outputs.component.scss
src/theme/_tables.scss

Fixes #428 
Changes:
- The problem with long names in the outputs page is solved.

Fix problem with long names

---

src/app/components/layout/loading-content/loading-content.component.html
src/app/components/layout/loading-content/loading-content.component.ts
src/app/components/pages/history/history.component.html
src/app/components/pages/history/history.component.ts
src/app/components/pages/settings/blockchain/blockchain.component.html
src/app/components/pages/settings/blockchain/blockchain.component.ts
src/app/components/pages/settings/outputs/outputs.component.html
src/app/components/pages/settings/outputs/outputs.component.ts
src/app/components/pages/settings/pending-transactions/pending-transactions.component.html
src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
src/app/services/price.service.ts
src/app/services/wallet/history.service.ts
src/app/services/wallet/spending.service.ts
src/assets/i18n/en.json
src/assets/i18n/es.json

Changes:
- Now `PriceService` retries to get the price in a shorter amount of time if a connection error happens.
- Now `LoadingContentComponent` can also show error messages.
- Now if there is an error while loading the data in `HistoryComponent`, `BlockchainComponent`, `OutputsComponent` or `PendingTransactionsComponent` an error message is shown to the user, instead of showing the loading animation forever (as it happened until now).
- Fixes a problem that prevent the data on `OutputsComponent` from being updated if the user first opened the page to see the data of a particular address and then selected the option to see the data of all wallets.

UX improvements

---

src/app/components/layout/header/header.component.ts
src/app/components/layout/header/top-bar/top-bar.component.html
src/app/components/layout/header/top-bar/top-bar.component.scss
src/app/components/layout/header/top-bar/top-bar.component.ts
src/app/components/pages/settings/pending-transactions/pending-transactions.component.html
src/app/components/pages/settings/pending-transactions/pending-transactions.component.scss
src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.ts
src/app/services/blockchain.service.ts
src/app/services/cipher.provider.ts
src/app/services/clipboard.service.ts
src/app/services/wallet/balance.service.ts
src/assets/i18n/en.json
src/styles.scss

Fixes #460 
Changes:
- The first item of the top right menu is no longer selected. The change also implies that the menu is again shown touching the right edge of the browser, since there is no way to set the position of the menu and the method that was previously used made the menu to always be displayed with the first item selected. The problem originated because the Material library always shows the first item selected if it does not detect real mouse interaction ( https://github.com/angular/material2/blob/master/src/lib/menu/menu-trigger.ts ), so the problem is too complex for the little importance of the matter.
- The amount of coins in the pending transactions page is now aligned to the right, to maintain consistency with the other pages.
- The text that indicates how much time has …

General improvements

---

package-lock.json
package.json
src/app/app.datatypes.ts
src/app/components/layout/header/header.component.html
src/app/components/layout/header/header.component.ts
src/app/components/pages/history/history.component.html
src/app/components/pages/send-skycoin/send-form/send-form.component.html
src/app/components/pages/send-skycoin/send-form/send-form.component.ts
src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html
src/app/components/pages/wallets/wallet-detail/wallet-detail.component.html
src/app/components/pages/wallets/wallets.component.html
src/app/services/wallet/balance.service.ts
src/app/services/wallet/history.service.spec.ts
src/app/services/wallet/history.service.ts
src/app/services/wallet/spending.service.spec.ts
src/app/services/wallet/spending.service.ts
src/app/services/wallet/wallet.service.cipher.spec.ts
src/app/services/wallet/wallet.service.spec.ts
src/app/services/wallet/wallet.service.ts

This pr is partially based on https://github.com/skycoin/skycoin/pull/1881, but includes additional changes
Changes:
- Use bignumber.js to calculate the values of the coins and the hours, to avoid problems with how JavaScript handle decimals.
- Fix the unit tests.

Use bignumber.js for coin and hour values

---

src/app/services/wallet/spending.service.ts

Changes:
Now if the node is v0.25 or higher, the burn factor is consulted using the `/api/v1/health` API endpoint before creating a transaction. The number of hours that must be burned is equal to the total amount of hours in the inputs divided by the `user_verify_transaction.burn_factor` property returned by the API call, rounded up.
If the node is v0.24, it is assumed that the number of hours that must be burned is half the total amount of hours in the inputs, rounded up.
As before, the unburned hours are divided equally among the outputs, which can be one or two (depending on whether there are change coins or not).

Use the correct factor burn

---

src/app/components/pages/settings/pending-transactions/pending-transactions.component.html
src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
src/app/services/wallet/spending.service.ts

Fixes #486 
Changes:
- Use BigNumber where missing

Use BigNumber where missing

---

README.md

Changes:
- This pr adds to `README.md` notes about the tests that should be done before launching a new release.

Add pre-release notes

---

src/app/components/pages/history/history.component.html
src/app/components/pages/history/history.component.scss
src/app/components/pages/history/history.component.spec.ts
src/app/components/pages/history/history.component.ts
src/app/components/pages/wallets/wallet-detail/wallet-detail.component.html
src/assets/i18n/en.json
src/assets/i18n/es.json
src/styles.scss

Fixes #513 
Changes:
- Now it is possible to limit the history page to certain addresses or wallets.
Implementation of https://github.com/skycoin/skycoin/pull/2116 for the web wallet. It includes several changes nedded for the web wallet and responsive design.

 Allow to filter the transaction history

---

MULTICOIN-INFO.md
electron/src/electron-main.js
src/app/coins/basecoin.ts
src/app/coins/skycoin.coin.ts
src/app/coins/test.coin.ts
src/app/components/layout/header/header.component.html
src/app/services/price.service.ts
src/app/utils/test-mocks.ts

Changes:
- Now the UI gets the price in USD from the Coin Paprika API, instead of the CMC API.
Implementation of https://github.com/skycoin/skycoin/pull/2158 for the web wallet.

Migrate from CMC to Coin Paprika

---

.travis.yml
README.md

Changes:
- Update travis to `xenial`
- Add project banner to readme

update travis add banner to readme
