src/app/components/pages/history/history.component.html, src/app/components/pages/history/transaction-detail/transaction-detail.component.html
Fixes #82 
Changes:
- update currency pipe option to remove warning (pages: history, transaction-detail)
=> Issue #82: Remove currency pipe warning (browser console)

src/app/services/cipher.provider.ts, src/app/services/wallet.service.spec.ts, src/app/services/wallet.service.ts
Fixes #72: Transactions are created without inputs, outputs and signatures
Changes:
- JSON.stringify is being called only ones for the transaction's inputs and outputs for the Cipher.PrepareTransaction.
=> #72: Transactions are created without inputs, outputs and signatures

src/app/services/wallet.service.ts
Fixes #87 
Changes:
- throw Error instead of reject Promise in case when seed is incorrect;
=> Issue #87: Problems when trying to unlock a wallet with an incorrect seed

src/app/components/pages/settings/outputs/outputs.component.html, src/app/components/pages/settings/outputs/outputs.component.scss, src/app/components/pages/settings/pending-transactions/pending-transactions.component.html, src/app/components/pages/settings/pending-transactions/pending-transactions.component.scss
Fixes #111 
Changes:
- Remove redundant titles on the outputs and pending transactions pages.
=> Issue #111: Duplicate title

e2e/wallets.e2e-spec.ts, e2e/wallets.po.ts, src/app/components/pages/wallets/address-detail/wallet-detail.component.html, src/app/components/pages/wallets/address-detail/wallet-detail.component.spec.ts, src/app/components/pages/wallets/address-detail/wallet-detail.component.ts, src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.ts
Fixes #112 
Changes:
- The option to add an address is always visible
- Toaster notification added on failed attempt to add address to the wallet
- Unlock wallet modal appears on attempt to add address to locked wallet
- Unit tests has been adjusted
- e2e test has been added to cover additional logic
- broken e2e tests has been fixed (create wallet and hide empty addresses tests were broken)
=> Issue #112: The option to add an address should be always visible

src/app/components/pages/settings/pending-transactions/pending-transactions.component.html, src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
Fixes #110 
Changes:
- convert coins using `parseFloat()` instead of `parseInt()`;
- add pipe to show decimals on the page.
=> Issue #110: Show decimals was fixed

src/app/services/wallet.service.ts
Fixes #141
Changes:
- WalletService.loadBalances() method has been removed from the wallet service constructor, since in it being run after uploading all block chains.
=> Issue #141: WalletService.loadBalances() called twice

proxy.config.js, src/environments/environment.prod.ts, src/environments/environment.ts
Fixes #138 
Changes:
-  "/api/v1/" has been used for all the connections to the node
=> Issue #138: Use /api/v1/ prefix for API endpoints

src/app/app.datatypes.ts, src/app/app.module.ts, src/app/components/layout/button/button.component.html, src/app/components/layout/button/button.component.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.html, src/app/components/pages/send-skycoin/send-form/send-form.component.scss, src/app/components/pages/send-skycoin/send-form/send-form.component.spec.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.ts, src/app/components/pages/send-skycoin/send-skycoin.component.html, src/app/components/pages/send-skycoin/send-skycoin.component.spec.ts, src/app/components/pages/send-skycoin/send-skycoin.component.ts, src/app/components/pages/send-skycoin/send-verify/send-verify.component.html, src/app/components/pages/send-skycoin/send-verify/send-verify.component.scss, src/app/components/pages/send-skycoin/send-verify/send-verify.component.spec.ts, src/app/components/pages/send-skycoin/send-verify/send-verify.component.ts, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.scss, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.spec.ts, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.ts, src/app/services/wallet.service.spec.ts, src/app/services/wallet.service.ts
Fixes #148 
Changes:
- splitted up the sendSkycoin method into two separate methods: createTransaction() and injectTransaction();
- added three new components: SendForm, SendVerify, TransactionInfo
- verification page is shown before actual sending of coins;
- added two separate data types: NormalTransaction and PreviewTransaction (both of them extends Transaction);
- 100000 multiplier is used when transaction is going to be posted (not in createTransaction);
- updated balance after transaction has been posted;
- added/updated appropriate unit tests;
=> Issue #148: Add a transaction verification screen

src/app/components/pages/history/history.component.scss
Fixes #174
Changes:
- colour opacity of the dates on the history page.
=> #174: The dates on the history page are barely visible

e2e/wallets.po.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.spec.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts, src/app/components/pages/wallets/create-wallet/create-wallet.component.spec.ts, src/app/components/pages/wallets/create-wallet/create-wallet.component.ts, src/app/services/wallet.service.ts
Fixes #172 
Changes:
- `walletService.create()`: add check if user creates a wallet with already existing seed;
- `walletService.create()` returns `promise<void>`, instead of `void` to have simple ability of error handling;
- update unit tests;
- update e2e tests;
=> #172: Prevent the user from adding more than one wallet with the same seed

src/app/components/pages/history/history.component.html
Fixes #192 
Changes:
- The history page shows the 'Calculated at the current rate' alert about the USD values
=> #192: The history page does not show the alert about the USD values

src/app/app.datatypes.ts, src/app/components/pages/send-skycoin/send-verify/send-verify.component.spec.ts, src/app/components/pages/send-skycoin/send-verify/send-verify.component.ts, src/app/services/wallet.service.ts
Fixes #188 
Changes:
- rename method `ascii_to_hexa` to `convertAsciiToHexa` to be consistent in naming;
- fix the bug from the issue #190 (multiplied coins);
- move encoding of transaction by cipher provider from send-verify page to send-form page.
=> #188: Encode the transaction before displaying the preview

src/app/components/pages/history/history.component.html, src/app/components/pages/history/history.component.ts
Fixes #212
Changes:
- added event handler on click event to show QR code.
=> #212: The QR buttons on the history page are not clickable

src/app/services/wallet.service.spec.ts
Fixes #165
Changes:
- added unit-tests for `walletService.createTransaction()`
=> #165: Add tests for the transaction verification screen

src/app/services/wallet.service.ts
Fixes #225
Changes:
- If there is an error when connecting to the server, the balance will be updated again after 20 seconds (the timer is restarted as if there were pending transactions).
- The number of minutes that has passed since the last balance update is rounded down.
=> Fix balance update problems

src/app/components/pages/send-skycoin/send-form/send-form.component.spec.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.ts
Fixes #236
Changes:
- close `MatSnackBar` when user navigates from send coins form to another page.
=> #236: Close the MatSnackBar when navigatin from the send coins form

src/app/utils/web-workers-helper.ts, src/assets/scripts/workers/generate-addresses.worker.js
Fixes #263 
Changes:
- Adds `WebWorkersHelper` to help run the web workers.
- Adds `generate-addresses.worker.js` as an example web woker.
This PR aims to define an standard procedure for the creation of web workers in this repository.
This PR includes `generate-addresses.worker.js` as an example of how to create a web worker. It is simply a JavaScript file that follows the standard format for creating web workers. The example simply creates an address from a seed, similarly (though more simply) to how `CipherProvider.generateAddress` does it. The example shows how to access the `Cipher` object from a web worker.
The web worker is not coded in TypeScript because that would imply making relatively complicated changes to Webpack, which is too much trouble considering the simplicity of the …
=> Base for web workers

src/app/components/layout/header/header.component.ts
Fixes #206
Changes:
- "querying" loading animation has been added when balance has not yet been obtained.
=> #260: Show the loading animation until geting the balance for the first time

.travis.yml
Fixes #272 
Changes:
- Add "develop" to the list of branches taken into account by Travis.
=> Make Travis work in the develop branch

e2e/wallets.e2e-spec.ts, e2e/wallets.po.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts, src/app/components/pages/wallets/create-wallet/create-wallet.component.ts
Fixes #276 
Changes:
- Added ability to create a wallet with a one letter name in the wizard for "onboarding-create-wallet.component.ts" and "create-wallet.component.ts" components
- Fixed e2e tests
=> #276: Should be able to create a wallet with a one letter name in the wizard

src/app/components/layout/button/button.component.html, src/app/components/layout/button/button.component.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.html, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.spec.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts
Fixes #292 
Changes:
- Spinner in loading spinner is displayed on the "Create" button when creating a wallet in the wizard
- "Skip" button is disabled while creating a wallet
- "spinnerStyle" input property has been added to the "button.component" in order to use alternative spinner color (by default it was black spinner on black "create" button)
- minor refactoring of the involved components
=> #292: Show the loading spinner in the wizard

src/app/components/pages/wallets/create-wallet/create-wallet.component.html
Fixes #293 
Changes:
- "Seed" text area has been aligned with "Name" and "Confirm seed" fields on the "Create wallet" page
=> #293: Incorrect alignments on the create wallet page

src/app/components/layout/header/header.component.html, src/app/components/layout/header/header.component.spec.ts, src/app/components/layout/header/header.component.ts, src/app/components/pages/history/history.component.html, src/app/components/pages/history/history.component.spec.ts, src/app/components/pages/history/history.component.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.html, src/app/components/pages/send-skycoin/send-form/send-form.component.spec.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.ts, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.spec.ts, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.ts, src/app/components/pages/settings/outputs/outputs.component.html, src/app/components/pages/settings/outputs/outputs.component.spec.ts, src/app/components/pages/settings/outputs/outputs.component.ts, src/app/components/pages/settings/pending-transactions/pending-transactions.component.html, src/app/components/pages/settings/pending-transactions/pending-transactions.component.spec.ts, src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts, src/app/components/pages/wallets/wallets.component.html, src/app/components/pages/wallets/wallets.component.spec.ts, src/app/components/pages/wallets/wallets.component.ts, src/assets/i18n/en.json
Fixes #334 
Changes:
- show coin symbol from coin service instead of translated text;
- show hours name from coin service instead of translated text;
- fix appropriate unit-tests;
- removed unused text from `en.json`.
=> #334: Get the names of the coins from CoinService

src/app/services/wallet.service.ts
Fixes #354 
Changes:
- Filtering of wallets has been fixed considering usage of different coins.
=> #354: Bug if more than one wallet has the same seed

src/app/coins/basecoin.ts, src/app/coins/skycoin.coin.ts, src/app/coins/test.coin.ts, src/app/components/layout/header/header.component.html, src/app/components/layout/header/top-bar/top-bar.component.html, src/app/components/layout/header/top-bar/top-bar.component.spec.ts, src/app/components/layout/header/top-bar/top-bar.component.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.spec.ts, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.spec.ts, src/app/components/pages/settings/blockchain/blockchain.component.html, src/app/components/pages/settings/blockchain/blockchain.component.spec.ts, src/app/components/pages/settings/blockchain/blockchain.component.ts, src/app/components/pages/wallets/wallets.component.spec.ts, src/assets/i18n/en.json
Fixes #349 
Changes:
- "coinExplorer" property has been added to the "BaseCoin" class
- Link to coin explorer has been added to the "sky" and "test" coins
- Header's "Choose coin:" hard code has been replaced with the translated version
- "CoinService" has been used to replace "SKY" and "Coin" hours to appropriate coin entities
- Fixed unit tests
=> #349: Show the name of the selected coin

src/app/services/coin.service.ts
Fixes #367 
Changes:
- currently selected coin is being stored in the sessionStorage as well in order to be able to work with different coins in the separate tabs
=> #367: Save the selected coin in every tab

e2e/onboarding-create.po.ts, e2e/transactions.po.ts, src/app/app.module.ts, src/app/services/api.service.spec.ts, src/app/services/api.service.ts, src/app/services/price.service.spec.ts, src/app/services/price.service.ts
Changes in the first commit:
- `Http` has been replaced with `HttpClient`, as `Http` has ben deprecated. The change was also made in `PriceService` to completely delete `Http`.
- The querystrings are created using `HttpParams`, instead of manually adding the text to the URL. 
- The type was added to various parameters and functions that did not have it.
- The function for processing the errors now returns the `error.error` text by default, because before it returned the complete error and the text of `error.message` was being used by default by the components, which was not adequate. For example, this error was being displayed:
with the change now this error is shown:
- Small modifications were made to the e2e tests because they were failing locally.
In general, this pr was made while …
=> Code cleaning - ApiService

.angular-cli.json, e2e/onboarding-create.po.ts, e2e/wallets.po.ts, package.json, src/app/app.module.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.spec.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts, src/app/components/pages/wallets/create-wallet/create-wallet.component.spec.ts, src/app/components/pages/wallets/create-wallet/create-wallet.component.ts, src/app/components/pages/wallets/scan-addresses/scan-addresses.component.html, src/app/components/pages/wallets/scan-addresses/scan-addresses.component.spec.ts, src/app/components/pages/wallets/scan-addresses/scan-addresses.component.ts, src/app/services/api.service.ts, src/app/services/blockchain.service.ts, src/app/services/wallet/balance.service.ts, src/app/services/wallet/wallet.service.spec.ts, src/app/services/wallet/wallet.service.ts, src/app/utils/index.ts, src/app/utils/test-mocks.ts, src/assets/i18n/en.json, src/assets/i18n/es.json, src/environments/environment.e2e.ts, src/environments/environment.prod.ts
Changes:
- When loading a wallet, the addresses are scanned and those with transactions are added. The procedure scans addresses sequentially and stops when it have already reviewed 10 consecutive addresses without transactions or when it have already reviewed a total of 100 addresses, whichever happens first.
- Some fixes for the e2e tests.
=> Scan the addresses when loading a wallet

e2e/onboarding-create.e2e-spec.ts, e2e/onboarding-create.po.ts, e2e/send_sky.po.ts, e2e/transactions.po.ts, e2e/wallets.po.ts, src/app/app.module.ts, src/app/services/coin.service.ts
In preparation for uploading the wallet to a server for testing, this PR disables Testcoin. This means that the options for changing the coin will be hidden in the UI, since only one coin would be available (Skycoin). It is possible to reactivate Testcoin simply by uncommenting a line of code, in case it is necessary for testing.
Update 1: now Testcoin is only hidden in production builds
Update 2: the style of the URLs was changed to `HashLocationStrategy`, to avoid having to make additional configurations to the server.
=> Prepare for a test server

README.md, docker/images/Dockerfile
Fixes #483 
Changes: Remove yarn from README file and use npm instead of yarn to build docker image
-
=> Remove yarn reference from Dockerfile and update Installation on README

src/app/app.module.ts, src/app/components/pages/settings/pending-transactions/pending-transactions.component.spec.ts, src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts, src/app/services/api.service.ts, src/app/services/blockchain.service.spec.ts, src/app/services/blockchain.service.ts, src/app/services/globals.service.ts, src/app/services/wallet/balance.service.ts, src/app/services/wallet/history.service.spec.ts, src/app/services/wallet/history.service.ts, src/app/services/wallet/spending.service.spec.ts, src/app/services/wallet/spending.service.ts, src/app/services/wallet/wallet.service.cipher.spec.ts, src/app/services/wallet/wallet.service.spec.ts, src/app/services/wallet/wallet.service.ts, src/app/utils/semver.spec.ts, src/app/utils/semver.ts, src/app/utils/test-mocks.ts
Fixes #160 
Changes:
- The connections to the node now use many of the improvements added in v0.25.0, Mainly the `verbose` argument and the ability to send long lists of addresses using POST.
- A way to determine the version of the node was created. This is currently used to maintain compatibility with the version 0.24.0 of the node and to use the new features only if the node is runnin v0.25.0 or higher. 
- The function responsible for sending POST requests was updated, to be able to send more than Json.
- The unit tests were updated to be compatible with the changes.
=> Use v0.25.0 api

src/app/coins/skycoin.coin.ts, src/app/coins/test.coin.ts, src/app/services/api.service.ts
Changes:
- Now the `/api/v1/` part is not necessary in the URLs of the nodes. This helps the UX when the user decides to change the URL and is a change that would be necessary anyway in the future, to be able to use the v2 API.
=> Improved URL management

e2e/onboarding-create.po.ts, src/app/components/layout/header/top-bar/top-bar.component.html, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.html, src/app/components/pages/send-skycoin/send-form/send-form.component.html, src/assets/i18n/en.json, src/theme/_modals.scss
This PR includes several simple changes that were proposed during the review for releasing a stable version.
Changes:
- When the option to open the explorer is selected, it is opened in a new tab. When doing this the `rel` parameter is used to avoid security problems.
- The font size of the confirmation modal window was changed.
- A problem in the text of the disclaimer was fixed.
- The field for entering the amount of coins to be sent, in the send coins form, is no longer of the type `number`, since that caused a problematic behavior with the mouse wheel.
- When the option to load a wallet is selected, in the onboarding page, the page title and the button text are changed.
=> Several small improvements

src/app/components/pages/send-skycoin/send-form/send-form.component.spec.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.ts, src/app/services/blockchain.service.ts, src/app/utils/test-mocks.ts
Changes:
-  The form for sending coins no longer checks if the number of coins has 6 or fewer decimal places, but validates if the number of decimal places is not greater than the amount currently activated in the node. The number of valid decimal places is obtained with a call to the `health` api endpoint
=> Validate the correct number of decimals

e2e/wallets.po.ts, src/app/app.datatypes.ts, src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.ts, src/app/components/pages/wallets/create-wallet/create-wallet.component.ts, src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.html, src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.scss, src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.ts, src/app/components/pages/wallets/wallet-detail/wallet-detail.component.ts, src/app/components/pages/wallets/wallets.component.html, src/app/components/pages/wallets/wallets.component.spec.ts, src/app/components/pages/wallets/wallets.component.ts, src/app/services/wallet/wallet.service.spec.ts, src/app/services/wallet/wallet.service.ts, src/app/utils/index.ts, src/assets/i18n/en.json, src/assets/i18n/es.json, src/styles.scss
During the last tests it became obvious that it is necessary to make it clear to the user that the web wallet does not save the seeds as the desktop wallet does and that it is absolutely necessary to safeguard the seeds or the funds could become inaccessible.
Changes:
- With this pr if the user tries to see the addresses of a newly created wallet the following modal window is displayed requesting the seed, in order to confirm if the user has safeguarded the seed:
- In the modal window the user must add an additional question mark at the end of the seed (it s indicated in the instructions text). This is to ensure that the user reads the instructions.
- Once the user places the seed correctly, the modal window is not shown again when the users tries to see the addresses of that wallet.
- …
=> Request the seed before being able to see the addresses

e2e/wallets.po.ts, src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.html, src/app/components/pages/wallets/unlock-wallet/unlock-wallet.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
Changes:
- With this PR, when the user creates a new wallet and tries to see the addresses, the modal window that asks the user to confirm the seed before continuing is still shown, but it is no longer ask to add a question mark at the end of the seed.
=> Stop asking for a question mark to confirm the seed

src/app/components/pages/settings/nodes/change-url/change-node-url.component.html, src/app/components/pages/settings/nodes/change-url/change-node-url.component.scss, src/app/components/pages/settings/nodes/change-url/change-node-url.component.spec.ts, src/app/components/pages/settings/nodes/change-url/change-node-url.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
Fixes #490
Changes:
- Now, when trying to change the URL of the node, the URL and the node version are verified with a call to the `/health` endpoint.
- Before making the URL change, the user can see some of the properties of the new node.
=> Validate custom node Urls

src/app/services/wallet/wallet.service.ts
Changes:
- This PR fixes a problem added in the PR that stoped saving the data in the production builds. The problem is that after adding the first wallet on the wizard, any newly added wallet do not appear in the wallet list.
=> Allow to add more wallets

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/services/cipher.provider.ts, src/app/utils/cipher-web-worker-helper.ts, src/assets/i18n/en.json, src/assets/i18n/es.json, src/assets/scripts/cipher-web-worker.js
Changes:
- Now the wallet checks if the browser allows to access the `crypto` library inside a worker. If the check fails, an error message is displayed to the user stating that the wallet is not compatible with the browser.
Just like https://github.com/skycoin/skycoin-web/pull/509, this change was already made in https://github.com/skycoin/skycoin-web/pull/506, but I'm putting it in a separate PR so it can be reviewed and merged more easily in case that PR takes a long time to be merged, so that the users can start testing the wallet in less time.
=> Check if the crypto library can be used inside a worker

src/app/services/wallet/spending.service.spec.ts, src/app/services/wallet/spending.service.ts
Fixes #512
Changes:
The function responsible for selecting the inputs when creating transactions was improved. The new operation is based on the `ChooseSpends` function of the Skycoin node and the `ChooseSpendsMaximizeUxOuts` strategy:
https://github.com/skycoin/skycoin/blob/69e60c21c6873079e3fccee08db5658fec91f52e/src/wallet/wallet.go#L1926-L2022
https://github.com/skycoin/skycoin/blob/69e60c21c6873079e3fccee08db5658fec91f52e/src/wallet/wallet.go#L1850-L1856
The procedure follows the following steps:
- The unspent output with more coins is added to the transaction (if there is more than one output with the same number of coins, the one with the fewest hours is used)
- If it is necessary to add more coins, unspent outputs without hours are added (ordered from the one with the fewest coins …
=> Improve the outputs selection procedure

README.md, src/app/components/pages/settings/nodes/change-url/change-node-url.component.html, src/app/components/pages/settings/nodes/change-url/change-node-url.component.ts, src/app/services/blockchain.service.ts
Changes:
- This PR fixes 2 problems when connecting to a v0.24.0 node. The first one is that the initial connection procedure failed, because node v0.24.x does not return the `maxDecimals` parameter when calling the `health` endpoint. The second one is that when changing the node URL, if that node is v0.24.x, the operation failed, because the `health` endpoint does not return the `burn_factor` and `coin` parameters.
- Information about the minimum version that a node must have in order to use it as a backend was added to the README.
=> Fix v0.24.0 compatibility

src/app/components/pages/history/history.component.html, src/app/components/pages/history/history.component.spec.ts, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.spec.ts
Fixes #514 
Changes:
- The dates are now displayed with the `yyyy/MM/dd` format.
Implementation of https://github.com/skycoin/skycoin/pull/2115 for the web wallet.
=> Use a generic date format on the UI

src/app/components/pages/send-skycoin/send-form/send-form.component.html
Fixes #523 
Changes:
- With this PR now the Select that allows to select the wallet in the form for sending coins also shows the Coin Hours balance.
Implementation of https://github.com/skycoin/skycoin/pull/2157 for the web wallet.
=> Show the Coin Hours in the simple form

src/app/components/pages/settings/pending-transactions/pending-transactions.component.html, src/app/components/pages/settings/pending-transactions/pending-transactions.component.scss, src/app/components/pages/settings/pending-transactions/pending-transactions.component.ts
Fixes #511 
Changes:
- Now the pending transactions page shows the number of hours, in a way similar to how the desktop wallet does it.
=> Show the number of hours on the pending transactions screen

src/app/app.datatypes.ts, src/app/components/pages/history/history.component.html, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.html, src/app/components/pages/send-skycoin/send-verify/transaction-info/transaction-info.component.ts, src/app/services/wallet/history.service.spec.ts, src/app/services/wallet/history.service.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
Fixes #522 
Changes:
- When coins were moved between wallet addresses, the history showed that the user sended as many coins as there were in the inputs. Now that case is treated differently, and the UI shows `Internally moved`, instead of `Sent` or `Received`.
Implementation of https://github.com/skycoin/skycoin/pull/2147 for the web wallet.
=> Improved transactions processing in the history

src/app/components/layout/header/header.component.html, src/app/components/layout/header/header.component.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.ts, src/app/services/blockchain.service.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
Fixes #515 
Changes:
- A warning is displayed while the database is still being synchronized.
- If the user attempts to send a transaction while the database is being synchronized, a warning is displayed and confirmation is requested.
Implementation of https://github.com/skycoin/skycoin/pull/2112 and https://github.com/skycoin/skycoin/pull/2145 for the web wallet.
=> Show a warning while the wallet is synchronizing

src/app/components/pages/wallets/create-wallet/create-wallet-form/create-wallet-form.component.scss
Changes:
- The warning icon is now at the top of the warning boxes, instead of the middle. This should help to have a greater consistency in the UI.
This is the web wallet equivalent of  https://github.com/skycoin/skycoin/pull/2256
=> Change the warning icon position

e2e/wallets.po.ts, src/app/app.datatypes.ts, src/app/components/pages/send-skycoin/send-form/send-form.component.html, src/app/components/pages/wallets/wallet-detail/wallet-detail.component.ts, src/app/services/cipher.provider.lib.spec.ts, src/app/services/cipher.provider.spec.ts, src/app/services/cipher.provider.ts, src/app/services/wallet/wallet.service.cipher.spec.ts, src/app/services/wallet/wallet.service.spec.ts, src/app/services/wallet/wallet.service.ts
Fixes #550 
Fixes #553 
Changes:
- Now the next seed for creating an address is stored in the `Wallet` object and not in the individual `Address` objects.
- The `Cannot read property 'decimalPlaces' of undefined` error in the form for sending coins was fixed.
- The unit tests have been updated.
=> Code fixes

.angular-cli.json, Makefile, electron/README.md, package.json, src/app/components/pages/settings/nodes/nodes.component.html, src/app/components/pages/settings/nodes/nodes.component.ts, src/environments/environment.e2e-prod.ts, src/environments/environment.e2e.ts, src/environments/environment.local.prod.ts, src/environments/environment.local.ts, src/environments/environment.prod.ts
Changes:
- Deactivates the option for changing the node URL in the nodes page. This does not happens if the wallet was compiled for being used from the local file system or Electron.
=> Deactivate the custom URLs for the nodes
